#!/usr/bin/env bash
nateInit () 
{ 
    aws codeartifact login --tool npm --domain nate-js --repository js --namespace @nate;
    aws ecr get-login-password --profile default | docker login --username AWS --password-stdin 847574585735.dkr.ecr.eu-west-1.amazonaws.com/nate-eu-west-1-builds-nodejs-ecr:nate-nodejs-v14
}
nateInit $@
